backend:
  name: git-gateway
  branch: master

local_backend: true
# change url to a link to the image you want to use, no file paths, must be a URL
logo_url: https://yopas.co.ug/images/yopasstransparentbg2.png

media_folder: 'public/images/post'
public_folder: '/images/post'


collections:
  
  - name: 'event'
    label: 'Event'
    folder: 'src/event'
    create: true
    slug: "{{pageName}}"
    fields:
      - { label: 'Page-Name-with-dashes-only', name: 'pageName', widget: 'string' }
      - { label: 'Event Title', name: 'eventTitle', widget: 'string' }
      - { label: 'Title Tag', name: 'titleTag', widget: 'string' }
      - { label: 'Description', name: 'eventDescription', widget: 'string' }
      - { label: 'Host', name: 'host', widget: 'string' }
      - { label: 'Amount in UGX', name: 'amountInUGX', widget: 'string' }
      - { label: 'Event Time', name: 'eventTime', widget: 'string' }

      - { label: 'Location', name: 'location', widget: 'string' }
      - { label: 'Date', name: 'eventDate', widget: 'datetime' }
      - { label: 'Tags', name: 'tags', widget: 'list', default: ['post'] }
      - { label: 'Featured Image', name: 'image', widget: 'image' }
      - { label: 'Image Caption', name: 'imageAlt', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'EventUrl', name: 'TicketLink', widget: 'string' }
  - name: 'blog'
    label: 'Blog'
    folder: 'src/blog'
    create: true
    slug: '{{pageName}}'
    fields:
      - { label: 'Page-Name-with-dashes-only', name: 'pageName', widget: 'string' }
      - { label: 'Blog Title', name: 'blogTitle', widget: 'string' }
      - { label: 'Title Tag', name: 'titleTag', widget: 'string' }
      - { label: 'Description', name: 'blogDescription', widget: 'string' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Tags', name: 'tags', widget: 'list', default: ['blog'] }
      - { label: 'Featured Image', name: 'image', widget: 'image' }
      - { label: 'Image Caption', name: 'imageAlt', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  

